Updated pipeline for release

diff --git a/.github/workflows/manual-release.yml b/.github/workflows/manual-release.yml
--- a/.github/workflows/manual-release.yml
+++ b/.github/workflows/manual-release.yml
@@ -13,6 +13,10 @@ on:
         description: 'Changelog notes'
         required: false
 
+permissions:
+  contents: write
+  packages: write
+
 jobs:
   tag-version:
     name: Tag Version
@@ -26,17 +30,17 @@ jobs:
     if: contains(['major', 'minor', 'patch'], ${{ github.event.inputs.bumpPart }})
     steps:
       - name: Checkout source
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       
-      - name: Fetch and set app info
+      - name: Get app info
         id: appinfo
         run: |
           APP_NAME=$(cat app.manifest | jq -r '.info.id.name' | tr _ - )
-          echo "::set-output name=app_name::${APP_NAME}"
+          echo "app_name=${APP_NAME}" >> $GITHUB_OUTPUT
 
       - name: Bump version and push tag
         id: bumpversion
-        uses: jaumann/github-bumpversion-action@v0.0.7
+        uses: jasonamyers/github-bumpversion-action@v1.0.4
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: ${{ github.event.inputs.bumpPart }}
@@ -46,11 +50,11 @@ jobs:
           remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
           git push "${remote_repo}" HEAD:${GITHUB_REF} --follow-tags --tags
       
-      - name: Get sha
+      - name: Get SHA
         id: sha
         run: |
           sha_new=$(git rev-parse HEAD)
-          echo "::set-output name=sha::$sha_new"
+          echo "sha=${sha_new}" >> $GITHUB_OUTPUT
   
   build:
     name: Generate App Bundle
@@ -58,7 +62,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           ref: ${{ needs.tag-version.outputs.new_sha }}
           fetch-depth: 0
@@ -70,12 +74,12 @@ jobs:
       - name: Bundle app source
         run: |
           mkdir dist
-          tar -zcvf dist/${{ needs.tag-version.outputs.app_name }}-${{ needs.tag-version.outputs.version }}.tar.gz --exclude='.[^/]*' --exclude=./dist .
+          tar -zcvf dist/${{ needs.tag-version.outputs.app_name }}_v${{ needs.tag-version.outputs.version }}.tgz --exclude='.[^/]*' --exclude=./dist .
 
-      - uses: actions/upload-artifact@v2
+      - uses: actions/upload-artifact@v3
         with:
           name: app_tgz
-          path: dist/${{ needs.tag-version.outputs.app_name }}-${{ needs.tag-version.outputs.version }}.tar.gz
+          path: dist/${{ needs.tag-version.outputs.app_name }}_v${{ needs.tag-version.outputs.version }}.tgz
 
   release:
     name: Create Release
@@ -85,7 +89,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       
       - name: Fetch all tags
         run: |
@@ -103,7 +107,7 @@ jobs:
           else
             content="Initial release"
           fi
-          echo "::set-output name=message::${content}" 
+          echo "message=${content}" >> $GITHUB_OUTPUT
 
       - name: Create Release
         id: create_release
@@ -122,7 +126,7 @@ jobs:
           prerelease: false
 
       - name: Download artifact
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v3
         with:
           name: app_tgz
       
@@ -130,7 +134,7 @@ jobs:
         id: app-name
         run: |
           app_package=$(ls -1 *gz | xargs basename)
-          echo "::set-output name=package::${app_package}"
+          echo "package=${app_package}" >> $GITHUB_OUTPUT
       
       - name: Upload Release Asset
         id: upload-release-asset 
@@ -143,35 +147,35 @@ jobs:
           asset_name: ${{ steps.app-name.outputs.package }}
           asset_content_type: application/tgz
 
-  publish:
-    needs: release
-    name: Upload to Splunkbase
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: app_tgz
+  # publish:
+  #   needs: release
+  #   name: Upload to Splunkbase
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: app_tgz
       
-      - name: Get artifact name
-        id: app-name
-        run: |
-          app_package=$(ls -1 *gz | xargs basename)
-          echo "::set-output name=package::${app_package}"
+  #     - name: Get artifact name
+  #       id: app-name
+  #       run: |
+  #         app_package=$(ls -1 *gz | xargs basename)
+  #         echo "::set-output name=package::${app_package}"
 
-      - name: Test connectivity
-        run: |
-          if ! ${{ secrets.SPLUNKBASE_ID != '' }} ; then exit 1; fi
-          curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request GET "https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/"
+  #     - name: Test connectivity
+  #       run: |
+  #         if ! ${{ secrets.SPLUNKBASE_ID != '' }} ; then exit 1; fi
+  #         curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request GET "https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/"
 
-      # Ref: https://dev.splunk.com/enterprise/docs/releaseapps/splunkbase/submitcontentui/#Submit-content-to-Splunkbase-with-the-Release-API
-      # TODO This has to be tested on apps already public in Splunkbase 
-      - name: "Upload package to Splunkbase"
-        if: ${{ success() }}
-        run: |
-          mkdir build
-          tar -xf ${{ steps.app-name.outputs.package }} -C build
-          PACKAGE=$(ls build/*)
-          echo ${PACKAGE}
-          echo ${{ steps.app-name.outputs.package }}
-          curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request POST https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/new_release/ -F "files[]=@${PACKAGE}" -F "filename=${{ steps.app-name.outputs.package }}" -F "splunk_versions=${{ secrets.SPLUNKBASE_SPLUNK_VERSION }}" -F "visibility=true"
+  #     # Ref: https://dev.splunk.com/enterprise/docs/releaseapps/splunkbase/submitcontentui/#Submit-content-to-Splunkbase-with-the-Release-API
+  #     # TODO This has to be tested on apps already public in Splunkbase 
+  #     - name: "Upload package to Splunkbase"
+  #       if: ${{ success() }}
+  #       run: |
+  #         mkdir build
+  #         tar -xf ${{ steps.app-name.outputs.package }} -C build
+  #         PACKAGE=$(ls build/*)
+  #         echo ${PACKAGE}
+  #         echo ${{ steps.app-name.outputs.package }}
+  #         curl --fail -s -u ${{ secrets.SPLUNK_USER }}:${{ secrets.SPLUNK_PASS }} --request POST https://splunkbase.splunk.com/api/v1/app/${{ secrets.SPLUNKBASE_ID }}/new_release/ -F "files[]=@${PACKAGE}" -F "filename=${{ steps.app-name.outputs.package }}" -F "splunk_versions=${{ secrets.SPLUNKBASE_SPLUNK_VERSION }}" -F "visibility=true"
